apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}-backend
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.backend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/backend-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Release.Name }}-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.deployment.healthCheck.livenessProbe.httpGet.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-backend-config
            - secretRef:
                name: {{ .Release.Name }}-backend-secret
          resources:
            {{- toYaml .Values.backend.deployment.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.backend.deployment.healthCheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.deployment.healthCheck.readinessProbe | nindent 12 }}
      serviceAccountName: {{ .Values.security.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      {{- with .Values.networkPolicy.backend.egress }}
      egress:
        {{- toYaml . | nindent 8 }}
      {{- end }}