apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}-frontend
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Release.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.deployment.healthCheck.livenessProbe.httpGet.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-frontend-config
          resources:
            {{- toYaml .Values.frontend.deployment.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.frontend.deployment.healthCheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.deployment.healthCheck.readinessProbe | nindent 12 }}
      serviceAccountName: {{ .Values.security.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      {{- with .Values.networkPolicy.frontend.egress }}
      egress:
        {{- toYaml . | nindent 8 }}
      {{- end }}