{{- if .Values.database.enabled }}
{{- if eq .Values.database.type "external" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}-database
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
{{- end }}
{{- end }}