{{- if and .Values.security.serviceAccount.enabled .Values.security.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.security.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}