apiVersion: v1
kind: Secret
metadata:
  name: todo-backend-secret
  namespace: todo
  labels:
    app: todo-backend
type: Opaque
stringData:
  secret-key: "bf84996e7821a6617798fd0f189133cdcb1773b9910cc5107b64a09277cbda6c"