apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  namespace: todo
  labels:
    app: todo-backend
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: todo-backend
    tier: backend