@echo off
echo Starting Backend...
start cmd /k "cd backend && .\venv\Scripts\activate && uvicorn main:app --reload --port 8000"
echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"
echo Both servers starting. Access frontend at http://localhost:3000
