apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-database-pvc
  namespace: todo
  labels:
    app: todo-database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi