apiVersion: v1
kind: Secret
metadata:
  name: todo-database-secret
  namespace: todo
  labels:
    app: todo-database
type: Opaque
stringData:
  database-url: "postgresql://neondb_owner:npg_Fgza3YAJV9qT@ep-snowy-wave-aino2mts-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"